AWSTemplateFormatVersion: '2010-09-09'
Description: Parent Stack

Parameters:
  TransitGatewayName:
    Type: String
    Default: "dx-vpc-non-prod-sandbox-tgw"

  AmazonSideAsn:
    Type: Number
    Default: '64512'

  AutoAcceptSharedAttachments:
    Type: String
    AllowedValues: 
      - enable
      - disable
    Default: enable

  DefaultRouteTableAssociation:
    Type: String
    AllowedValues: 
      - "enable"
      - "disable"
    Default: "disable"

  DefaultRouteTablePropagation:
    Type: String
    AllowedValues: 
      - "enable"
      - "disable"
    Default: "disable"

  DnsSupport:
    Type: String
    AllowedValues: 
      - "enable"
      - "disable"
    Default: "enable"

  VpnEcmpSupport:
    Type: String
    AllowedValues: 
      - "enable"
      - "disable"
    Default: "disable"

  MulticastSupport:
    Type: String
    AllowedValues: 
      - "enable"
      - "disable"
    Default: "disable"

  CoreRtName:
    Type: String
    Default: core

  SpokeRtName:
    Type: String
    Default: spoke

  EnableRamShare:
    Type: String
    AllowedValues: 
      - "enable"
      - "disable"
    Default: "disable"

  RamShareName:
    Type: String
    Default: "tgw-share"

  RamPrincipals:
    Type: CommaDelimitedList
    Default: '111111111111,222222222222'

  # Tags
  Domain:
    Type: String
    Default: 'test'

  Division:
    Type: String
    Default: ade

  Program:
    Type: String
    Default: testing

  Team:
    Type: String
    Default: sre

  Environment:
    Type: String
    Default: dev

Conditions:
  HasNameOverride: !Not [!Equals [!Ref TransitGatewayName, ""]]

Resources:
  TransitGatewayNested:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://cloudformation-module-template.s3.eu-west-2.amazonaws.com/infrastructure-templates/modules/transit-gateway/transit-gateway-template.yaml"

      Parameters:
        # Core TGW parameters (must match child template parameter names)
        TransitGatewayName: !If
          - HasNameOverride
          - !Ref TransitGatewayName
          - !Sub "${Environment}-transit-gateway"
        AmazonSideAsn: !Ref AmazonSideAsn
        AutoAcceptSharedAttachments: !Ref AutoAcceptSharedAttachments
        DefaultRouteTableAssociation: !Ref DefaultRouteTableAssociation
        DefaultRouteTablePropagation: !Ref DefaultRouteTablePropagation
        DnsSupport: !Ref DnsSupport
        VpnEcmpSupport: !Ref VpnEcmpSupport
        MulticastSupport: !Ref MulticastSupport
        CoreRtName: !Ref CoreRtName
        SpokeRtName: !Ref SpokeRtName

        # RAM share
        EnableRamShare: !Ref EnableRamShare
        RamShareName: !Ref RamShareName
        RamPrincipals: !Join [",", !Ref RamPrincipals]

        # --- VPC ATTACHMENT 1 (REQUIRED) ---
        Vpc1Name: "shared-svcs"
        Vpc1Id: "vpc-0ca2e373d8f3f78fc"
        Vpc1SubnetIds: "subnet-05dae123bbce38a09"
        Vpc1AssociateWithRt: "core"
        Vpc1PropagateToRt: "spoke"

        # --- VPC ATTACHMENT 2 (REQUIRED) ---
        Vpc2Name: "app-a"
        Vpc2Id: "vpc-0d68d2e8f175ff319"
        Vpc2SubnetIds: "subnet-0ea15c2cba1ec2b26"
        Vpc2AssociateWithRt: "spoke"
        Vpc2PropagateToRt: "core"

        # --- VPC ATTACHMENT 3 (optional) ---
        Vpc3Enabled: "true"
        Vpc3Name: "app-b"
        Vpc3Id: "vpc-0ddd4844146677bec"
        Vpc3SubnetIds: "subnet-06426201bd95c0e23"
        Vpc3AssociateWithRt: "spoke"
        Vpc3PropagateToRt: "core"

        # Tags
        Domain: !Ref Domain
        Division: !Ref Division
        Program: !Ref Program
        Team: !Ref Team

Outputs:
  TransitGatewayId:
    Value: !GetAtt TransitGatewayNested.Outputs.TransitGatewayId

  CoreRouteTableId:
    Value: !GetAtt TransitGatewayNested.Outputs.CoreRouteTableId

  SpokeRouteTableId:
    Value: !GetAtt TransitGatewayNested.Outputs.SpokeRouteTableId
