- ParameterKey: TransitGatewayName
  ParameterValue: "dx-vpc-non-prod-sandbox-tgw" 
- ParameterKey: AmazonSideAsn 
  ParameterValue: "64512" 
- ParameterKey: AutoAcceptSharedAttachments 
  ParameterValue: "enable" 
- ParameterKey: DefaultRouteTableAssociation 
  ParameterValue: "disable" 
- ParameterKey: DefaultRouteTablePropagation 
  ParameterValue: "disable" 
- ParameterKey: DnsSupport 
  ParameterValue: "enable" 
- ParameterKey: VpnEcmpSupport 
  ParameterValue: "disable" 
- ParameterKey: MulticastSupport 
  ParameterValue: "disable" 
- ParameterKey: CoreRtName 
  ParameterValue: "core" 
- ParameterKey: SpokeRtName 
  ParameterValue: "spoke" 
- ParameterKey: EnableRamShare 
  ParameterValue: "false" 
- ParameterKey: RamShareName 
  ParameterValue: "tgw-share" 
- ParameterKey: RamPrincipals 
  ParameterValue: "${RamPrincipals}"
- ParameterKey: Domain 
  ParameterValue: "${Domain}"
- ParameterKey: Division 
  ParameterValue: "${Division}"
- ParameterKey: Program 
  ParameterValue: "${Program}"
- ParameterKey: Team 
  ParameterValue: "${Team}"